### ISSUE TITLE
[Bug]同时使用鹊桥和floodgate-fabric无法启动服务端

### ISSUE THREAD

**Issue by qixun233** [17TheWord/QueQiao#26]
### 运行环境

Windows2016server  java17

### 鹊桥版本号

0.0.6

### 服务端信息

fabric1.20.1

### 复现问题的步骤

```markdown
启动服务器
加载完成鹊桥模组之后floodgate模组报错
```

### 错误日志

```markdown
[23:02:36] [main/INFO]: 正在加载插件...
[23:02:36] [main/INFO]: 已加载 0 个插件
[23:02:36] [main/INFO]: [MagicLib|Common]: Mod initialized - Version: 0.7.346+e235d92-stable
[23:02:36] [main/INFO]: [Memory Clearer Miss-not Ore Dict] Memory Clearer Miss-not Ore Dict is loaded!
[23:02:36] [main/INFO]: 正在启动
[23:02:36] [main/INFO]: 当前服务端类型为：模组服
[23:02:36] [main/INFO]: 正在寻找配置文件 config.yml...
[23:02:36] [main/INFO]: 配置文件 config.yml 路径为：C:\MC1.20.1生电\.\config\QueQiao\config.yml。
[23:02:36] [main/INFO]: 配置文件 config.yml 已存在，将读取配置项。
[23:02:36] [main/INFO]: 正在读取配置文件 config.yml...
[23:02:36] [main/INFO]: 读取配置文件 config.yml 成功。
[23:02:36] [main/INFO]: 初始化完成
[23:02:36] [main/INFO]: [ServerCore] Loaded V1.3.7+1.20.1!
[23:02:37] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@af43b0]
[23:02:37] [main/INFO]: WorldEdit for Fabric (version 7.2.15+6463-5ca4dff) is loaded
[23:02:37] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'floodgate'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
Caused by: org.geysermc.floodgate.shadow.guice.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingMethod]: RuntimeException: Failed to load the config! Try to delete the config file if this error persists
  at FloodgatePlatform.init(FloodgatePlatform.java:84)
  while locating FabricPlatform

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD

1 error

======================
Full classname legend:
======================
FabricPlatform:    "org.geysermc.floodgate.FabricPlatform"
FloodgatePlatform: "org.geysermc.floodgate.FloodgatePlatform"
========================
End of classname legend:
========================

	at org.geysermc.floodgate.shadow.guice.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:22) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: Failed to load the config! Try to delete the config file if this error persists
	at org.geysermc.floodgate.config.ConfigLoader.load(ConfigLoader.java:86) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:93) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5883124.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5883124.apply(<generated>) ~[?:?]
	at org.geysermc.floodgate.shadow.guice.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:22) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 6 more
Caused by: java.lang.IllegalStateException: Cannot update a configuration that is newer than the latest available config version
	at org.geysermc.configutils.updater.ConfigUpdater.update(ConfigUpdater.java:69) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.configutils.ConfigUtilities.update0(ConfigUtilities.java:152) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.configutils.ConfigUtilities.createOrUpdate(ConfigUtilities.java:113) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.configutils.ConfigUtilities.createAndMapOrUpdateAndMap(ConfigUtilities.java:86) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.configutils.ConfigUtilities.executeOn(ConfigUtilities.java:81) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.config.ConfigLoader.load(ConfigLoader.java:84) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:93) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5883124.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5883124.apply(<generated>) ~[?:?]
	at org.geysermc.floodgate.shadow.guice.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.shadow.guice.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:22) ~[%5B基岩互通%5Dfloodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 6 more
[23:02:44] [FTB Backups Config Watcher 0/INFO]: Config at C:\MC1.20.1生电\config\ftbbackups2.json has changed, reloaded!
```

**Comment by 17TheWord** [comment]
确定与鹊桥有关吗？我没看到有关鹊桥包的错误内容。移除鹊桥能正常启动吗？

**Comment by qixun233** [comment]
> 确定与鹊桥有关吗？我没看到有关鹊桥包的错误内容。移除鹊桥能正常启动吗？

是的，移除之后又能正常启动了（）
移除floodgate保留鹊桥可以启动
移除鹊桥保留floodgate也能启动服务器
但是二者同时在一起就会炸

**Comment by 17TheWord** [comment]
收到，后续会进行测试，可以先尝试日志读取程序

**Comment by 17TheWord** [comment]
发现在1.21.1正常启动
在1.20.1中，floodgate生成的配置文件是鹊桥的配置文件，暂不清楚是如何导致的

**Comment by 17TheWord** [comment]
长期无回复，将关闭该Issue，如有问题请reopen
