### ISSUE TITLE
[Bug] 消息解析异常

### ISSUE THREAD

**Issue by LinorInk** [17TheWord/QueQiao#28]
### 运行环境

Ubuntu 20.02

### 鹊桥版本号

QueQiao-spigot+1.13-0.0.1.jar

### 服务端信息

spigot 1.21

### 复现问题的步骤

```markdown
1. 开启Nonebot
2. 开启Minecraft spigot服务器
3. 等待Queqiao bot 连接到Nonebot
4. Nonebot端调用 bot.send(...)
5. Spigot 解析消息异常
```

### 错误日志

```markdown
NoneBot:
 Running Matcher(type='message', module=mcbot.plugins.tomc, lineno=39) failed.
Traceback (most recent call last):
  File "/home/midon/snap/NoneBot/mcbot/./bot.py", line 23, in <module>
    nonebot.run()
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/midon/snap/NoneBot/mcbot/mcbot/plugins/tomc/__init__.py", line 96, in handle_msg
    await bot.send(None, msg)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/adapters/minecraft/bot.py", line 81, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/adapters/minecraft/bot.py", line 49, in send
    return await bot.send_msg(message=message)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/midon/snap/NoneBot/mcbot/.venv/lib/python3.12/site-packages/nonebot/adapters/minecraft/adapter.py", line 229, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.minecraft.exception.NetworkError: <NetWorkError message=WebSocket call api send_msg timeout>

Spigot 端:
[12:01:35 WARN]: [QueQiao] 解析来自 ws://127.0.0.1:8080/minecraft/ws 的 WebSocket 消息时出现异常
[12:01:35 WARN]: [QueQiao] Cannot invoke "java.util.List.iterator()" because "myBaseComponentList" is null
[12:01:38 WARN]: Can't keep up! Is the server overloaded? Running 2824ms or 56 ticks behind
```

### 备注

在Spigot服务器监听到的消息发送到Nonebot是正常的，但是从Nonebot发送到Spigot就会出现消息解析异常

**Comment by 17TheWord** [comment]
发消息请使用send_msg

**Comment by LinorInk** [comment]
我调用的应该是这个，
await bot.send_msg(message=msg)

**Comment by 17TheWord** [comment]
打开鹊桥的debug，把收到的json粘过来我看看

**Comment by LinorInk** [comment]
debug: true # DEBUG，开启后会打印所有日志

debug已开启， 接收到的消息任然是：
[12:46:53 WARN]: [QueQiao] 解析来自 ws://127.0.0.1:8080/minecraft/ws 的 WebSocket 消息时出现异常
[12:46:53 WARN]: [QueQiao] Cannot invoke "java.util.List.iterator()" because "myBaseComponentList" is null

**Comment by 17TheWord** [comment]
好的，我下午会测试修复

**Comment by 17TheWord** [comment]
更新鹊桥至最新版本

**Comment by LinorInk** [comment]
更新Nonebot 鹊桥插件后问题决绝了👌
